# Generated by Django 4.2.3 on 2023-08-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_date', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('non active', 'Non Active')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='paid', max_length=4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.members')),
            ],
        ),
    ]
