# Generated by Django 4.2.3 on 2023-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_members_fee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='fee_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
